
export const TAROT_CARD_IMAGES = {
  "The Fool": "/cards/the_fool.jpg",
  "The Magician": "/cards/the_magician.jpg",
  "The High Priestess": "/cards/the_high_priestess.jpg",
  "The Empress": "/cards/the_empress.jpg",
  "The Emperor": "/cards/the_emperor.jpg",
  "The Hierophant": "/cards/the_hierophant.jpg",
  "The Lovers": "/cards/the_lovers.jpg",
  "The Chariot": "/cards/the_chariot.jpg",
  "Strength": "/cards/strength.jpg",
  "The Hermit": "/cards/the_hermit.jpg",
  "Wheel of Fortune": "/cards/wheel_of_fortune.jpg",
  "Justice": "/cards/justice.jpeg",
  "The Hanged Man": "/cards/the_hanged_man.jpg",
  "Death": "/cards/death.jpg",
  "Temperance": "/cards/temperance.jpg",
  "The Devil": "/cards/the_devil.jpg",
  "The Tower": "/cards/the_tower.jpg",
  "The Star": "/cards/the_star.jpg",
  "The Moon": "/cards/the_moon.jpg",
  "The Sun": "/cards/the_sun.jpg",
  "Judgement": "/cards/judgement.jpg",
  "The World": "/cards/the_world.jpg",
  "Ace of Wands": "/cards/ace_of_wands.jpg",
  "Two of Wands": "/cards/two_of_wands.jpg",
  "Three of Wands": "/cards/three_of_wands.jpg",
  "Four of Wands": "/cards/four_of_wands.jpg",
  "Five of Wands": "/cards/five_of_wands.jpg",
  "Six of Wands": "/cards/six_of_wands.jpg",
  "Seven of Wands": "/cards/seven_of_wands.jpg",
  "Eight of Wands": "/cards/eight_of_wands.jpg",
  "Nine of Wands": "/cards/nine_of_wands.jpg",
  "Ten of Wands": "/cards/ten_of_wands.jpg",
  "Page of Wands": "/cards/page_of_wands.jpg",
  "Knight of Wands": "/cards/knight_of_wands.jpg",
  "Queen of Wands": "/cards/queen_of_wands.jpg",
  "King of Wands": "/cards/king_of_wands.jpg",
  "Ace of Cups": "/cards/ace_of_cups.jpg",
  "Two of Cups": "/cards/two_of_cups.jpg",
  "Three of Cups": "/cards/three_of_cups.jpg",
  "Four of Cups": "/cards/four_of_cups.jpg",
  "Five of Cups": "/cards/five_of_cups.jpg",
  "Six of Cups": "/cards/six_of_cups.jpg",
  "Seven of Cups": "/cards/seven_of_cups.jpg",
  "Eight of Cups": "/cards/eight_of_cups.jpg",
  "Nine of Cups": "/cards/nine_of_cups.jpg",
  "Ten of Cups": "/cards/ten_of_cups.jpg",
  "Page of Cups": "/cards/page_of_cups.jpg",
  "Knight of Cups": "/cards/knight_of_cups.jpg",
  "Queen of Cups": "/cards/queen_of_cups.jpg",
  "King of Cups": "/cards/king_of_cups.jpg",
  "Ace of Swords": "/cards/ace_of_swords.jpg",
  "Two of Swords": "/cards/two_of_swords.jpg",
  "Three of Swords": "/cards/three_of_swords.jpg",
  "Four of Swords": "/cards/four_of_swords.jpg",
  "Five of Swords": "/cards/five_of_swords.jpg",
  "Six of Swords": "/cards/six_of_swords.jpg",
  "Seven of Swords": "/cards/seven_of_swords.jpg",
  "Eight of Swords": "/cards/eight_of_swords.jpg",
  "Nine of Swords": "/cards/nine_of_swords.jpg",
  "Ten of Swords": "/cards/ten_of_swords.jpg",
  "Page of Swords": "/cards/page_of_swords.jpg",
  "Knight of Swords": "/cards/knight_of_swords.jpg",
  "Queen of Swords": "/cards/queen_of_swords.jpg",
  "King of Swords": "/cards/king_of_swords.jpg",
  "Ace of Pentacles": "/cards/ace_of_pentacles.jpg",
  "Two of Pentacles": "/cards/two_of_pentacles.jpg",
  "Three of Pentacles": "/cards/three_of_pentacles.jpg",
  "Four of Pentacles": "/cards/four_of_pentacles.jpg",
  "Five of Pentacles": "/cards/five_of_pentacles.jpg",
  "Six of Pentacles": "/cards/six_of_pentacles.jpg",
  "Seven of Pentacles": "/cards/seven_of_pentacles.jpg",
  "Eight of Pentacles": "/cards/eight_of_pentacles.jpg",
  "Nine of Pentacles": "/cards/nine_of_pentacles.jpg",
  "Ten of Pentacles": "/cards/ten_of_pentacles.jpg",
  "Page of Pentacles": "/cards/page_of_pentacles.jpg",
  "Knight of Pentacles": "/cards/knight_of_pentacles.jpg",
  "Queen of Pentacles": "/cards/queen_of_pentacles.jpg",
  "King of Pentacles": "/cards/king_of_pentacles.jpg",
};
