export const TAROT_CARD_IMAGES: Record<string, string> = {
  "The Fool": "/zodiac/cards/the_fool.jpeg",
  "The Magician": "/zodiac/cards/the_magician.jpeg",
  "The High Priestess": "/zodiac/cards/the_high_priestess.jpeg",
  "The Empress": "/zodiac/cards/the_empress.jpeg",
  "The Emperor": "/zodiac/cards/the_emperor.jpeg",
  "The Hierophant": "/zodiac/cards/the_hierophant.jpeg",
  "The Lovers": "/zodiac/cards/the_lovers.jpeg",
  "The Chariot": "/zodiac/cards/the_chariot.jpeg",
  "Strength": "/zodiac/cards/strength.jpeg",
  "The Hermit": "/zodiac/cards/the_hermit.jpeg",
  "Wheel of Fortune": "/zodiac/cards/wheel_of_fortune.jpeg",
  "Justice": "/zodiac/cards/justice.jpeg",
  "The Hanged Man": "/zodiac/cards/the_hanged_man.jpeg",
  "Death": "/zodiac/cards/death.jpeg",
  "Temperance": "/zodiac/cards/temperance.jpeg",
  "The Devil": "/zodiac/cards/the_devil.jpeg",
  "The Tower": "/zodiac/cards/the_tower.jpeg",
  "The Star": "/zodiac/cards/the_star.jpeg",
  "The Moon": "/zodiac/cards/the_moon.jpeg",
  "The Sun": "/zodiac/cards/the_sun.jpeg",
  "Judgement": "/zodiac/cards/judgement.jpeg",
  "The World": "/zodiac/cards/the_world.jpeg",
  "Ace of Wands": "/zodiac/cards/ace_of_wands.jpeg",
  "Two of Wands": "/zodiac/cards/two_of_wands.jpeg",
  "Three of Wands": "/zodiac/cards/three_of_wands.jpeg",
  "Four of Wands": "/zodiac/cards/four_of_wands.jpeg",
  "Five of Wands": "/zodiac/cards/five_of_wands.jpeg",
  "Six of Wands": "/zodiac/cards/six_of_wands.jpeg",
  "Seven of Wands": "/zodiac/cards/seven_of_wands.jpeg",
  "Eight of Wands": "/zodiac/cards/eight_of_wands.jpeg",
  "Nine of Wands": "/zodiac/cards/nine_of_wands.jpeg",
  "Ten of Wands": "/zodiac/cards/ten_of_wands.jpeg",
  "Page of Wands": "/zodiac/cards/page_of_wands.jpeg",
  "Knight of Wands": "/zodiac/cards/knight_of_wands.jpeg",
  "Queen of Wands": "/zodiac/cards/queen_of_wands.jpeg",
  "King of Wands": "/zodiac/cards/king_of_wands.jpeg",
  "Ace of Cups": "/zodiac/cards/ace_of_cups.jpeg",
  "Two of Cups": "/zodiac/cards/two_of_cups.jpeg",
  "Three of Cups": "/zodiac/cards/three_of_cups.jpeg",
  "Four of Cups": "/zodiac/cards/four_of_cups.jpeg",
  "Five of Cups": "/zodiac/cards/five_of_cups.jpeg",
  "Six of Cups": "/zodiac/cards/six_of_cups.jpeg",
  "Seven of Cups": "/zodiac/cards/seven_of_cups.jpeg",
  "Eight of Cups": "/zodiac/cards/eight_of_cups.jpeg",
  "Nine of Cups": "/zodiac/cards/nine_of_cups.jpeg",
  "Ten of Cups": "/zodiac/cards/ten_of_cups.jpeg",
  "Page of Cups": "/zodiac/cards/page_of_cups.jpeg",
  "Knight of Cups": "/zodiac/cards/knight_of_cups.jpeg",
  "Queen of Cups": "/zodiac/cards/queen_of_cups.jpeg",
  "King of Cups": "/zodiac/cards/king_of_cups.jpeg",
  "Ace of Swords": "/zodiac/cards/ace_of_swords.jpeg",
  "Two of Swords": "/zodiac/cards/two_of_swords.jpeg",
  "Three of Swords": "/zodiac/cards/three_of_swords.jpeg",
  "Four of Swords": "/zodiac/cards/four_of_swords.jpeg",
  "Five of Swords": "/zodiac/cards/five_of_swords.jpeg",
  "Six of Swords": "/zodiac/cards/six_of_swords.jpeg",
  "Seven of Swords": "/zodiac/cards/seven_of_swords.jpeg",
  "Eight of Swords": "/zodiac/cards/eight_of_swords.jpeg",
  "Nine of Swords": "/zodiac/cards/nine_of_swords.jpeg",
  "Ten of Swords": "/zodiac/cards/ten_of_swords.jpeg",
  "Page of Swords": "/zodiac/cards/page_of_swords.jpeg",
  "Knight of Swords": "/zodiac/cards/knight_of_swords.jpeg",
  "Queen of Swords": "/zodiac/cards/queen_of_swords.jpeg",
  "King of Swords": "/zodiac/cards/king_of_swords.jpeg",
  "Ace of Pentacles": "/zodiac/cards/ace_of_pentacles.jpeg",
  "Two of Pentacles": "/zodiac/cards/two_of_pentacles.jpeg",
  "Three of Pentacles": "/zodiac/cards/three_of_pentacles.jpeg",
  "Four of Pentacles": "/zodiac/cards/four_of_pentacles.jpeg",
  "Five of Pentacles": "/zodiac/cards/five_of_pentacles.jpeg",
  "Six of Pentacles": "/zodiac/cards/six_of_pentacles.jpeg",
  "Seven of Pentacles": "/zodiac/cards/seven_of_pentacles.jpeg",
  "Eight of Pentacles": "/zodiac/cards/eight_of_pentacles.jpeg",
  "Nine of Pentacles": "/ziac/cards/nine_of_pentacles.jpeg",
  "Ten of Pentacles": "/zodiac/cards/ten_of_pentacles.jpeg",
  "Page of Pentacles": "/zodiac/cards/page_of_pentacles.jpeg",
  "Knight of Pentacles": "/zodiac/cards/knight_of_pentacles.jpeg",
  "Queen of Pentacles": "/zodiac/cards/queen_of_pentacles.jpeg",
  "King of Pentacles": "/zodiac/cards/king_of_pentacles.jpeg",
};
