
export type TranslationSet = {
    headerSubtitle: string;
    formZodiacLabel: string;
    formZodiacPlaceholder: string;
    formZodiacError: string;
    formQuestionLabel: string;
    formQuestionPlaceholder: string;
    buttonDefault: string;
    buttonLoading: string;
    resultsTitle: string;
    resultsReadingTitle: string;
    resultsLoadingText: string;
    footerCopyright: string;
    footerAbout: string;
    footerMission: string;
    footerFaq: string;
    footerTerms: string;
    footerPrivacy: string;
    aboutDialogTitle: string;
    aboutDialogContent: string;
    missionDialogTitle: string;
    missionDialogContent: string;
    faqDialogTitle: string;
    faqDialogContent: string;
    termsDialogTitle: string;
    termsDialogContent: string;
    privacyDialogTitle: string;
    privacyDialogContent: string;
    errorTitle: string;
    unknownError: string;
    countdownFinishedText: string;
    zodiacSignAries: string;
    zodiacSignTaurus: string;
    zodiacSignGemini: string;
    zodiacSignCancer: string;
    zodiacSignLeo: string;
    zodiacSignVirgo: string;
    zodiacSignLibra: string;
    zodiacSignScorpio: string;
    zodiacSignSagittarius: string;
    zodiacSignCapricorn: string;
    zodiacSignAquarius: string;
    zodiacSignPisces: string;
};

export const ALL_TRANSLATIONS: Record<string, TranslationSet> = {
    en: {
        headerSubtitle: "Discover what the stars and cards have in store for you. Enter your sign and question to get your personalized tarot reading.",
        formZodiacLabel: "Your Sign",
        formZodiacPlaceholder: "Select a sign...",
        formZodiacError: "You must select a valid zodiac sign.",
        formQuestionLabel: "Your question for the cards",
        formQuestionPlaceholder: "What is troubling or interesting you?",
        buttonDefault: "What do the cards say?",
        buttonLoading: "Shuffling the cards...",
        resultsTitle: "Your Cards of Fate",
        resultsReadingTitle: "Your Tarot Reading",
        resultsLoadingText: "The cards are being shuffled, your fate is being revealed...",
        footerCopyright: "All rights reserved.",
        footerAbout: "About Us",
        footerMission: "Our Mission",
        footerFaq: "FAQ",
        footerTerms: "Terms of Use",
        footerPrivacy: "Privacy Policy",
        aboutDialogTitle: "About The Quick Tarot App",
        aboutDialogContent: "Welcome to Quick Tarot, your digital window into the world of tarot cards. Our mission is to provide an intuitive and personalized tarot experience accessible to everyone, anywhere, anytime.\n\nUsing the power of artificial intelligence, our application generates unique and insightful tarot readings. Each reading is based on cards randomly drawn especially for you and your question, ensuring you receive a message that is meant for you.\n\nWe believe that tarot is not just about predicting the future, but a tool for self-reflection and a deeper understanding of the present. Whether you are looking for answers, inspiration, or simply want to explore your intuition, Quick Tarot is here to guide you.\n\nThank you for being part of our journey.",
        missionDialogTitle: "Our Mission",
        missionDialogContent: "Our mission is to demystify tarot and make it an accessible tool for personal growth and introspection. Through the fusion of ancient wisdom and modern technology, we aim to empower individuals to find clarity, make better decisions, and understand the deeper currents of their lives.\n\nWe strive to create a safe and supportive space where everyone can explore their intuition without prejudice.",
        faqDialogTitle: "Frequently Asked Questions",
        faqDialogContent: "Q: Are the readings truly random?\nA: Absolutely. For each new question, our system randomly selects three cards from a full 78-card deck, guaranteeing a unique and unbiased reading every time.\n\nQ: How often can I ask a question?\nA: To ensure the quality and meaningfulness of each reading, we have implemented a time limit. You can request a new reading every two minutes.\n\nQ: Is this real fortune-telling?\nA: We see tarot as a guide and a tool for self-reflection, rather than a concrete prediction of the future. The cards can help you see a situation from a new perspective and make decisions that are in line with your inner being.",
        termsDialogTitle: "Terms of Use",
        termsDialogContent: "By accessing and using the Quick Tarot application, you agree to the following terms:\n\n1. The service is provided 'as is'. Readings are generated by artificial intelligence and are for entertainment and introspective purposes only. They should not be considered professional, legal, medical, or financial advice.\n\n2. We assume no liability for any decisions you make based on the information obtained through our application.\n\n3. We reserve the right to modify or discontinue the service at any time without prior notice.\n\n4. We collect minimal data necessary for the application's functionality, as described in our privacy policy.",
        privacyDialogTitle: "Privacy Policy",
        privacyDialogContent: "This Privacy Policy explains how we collect, use, and protect your data.\n\n1. Data Collection: We only collect the necessary data for the application's functionality, such as your question and selected zodiac sign, which are not stored permanently. We use local storage in your browser to save your last reading and the time when you can request a new one.\n\n2. Google AdSense: We use Google AdSense to display advertisements. Google may use cookies to serve relevant ads based on your previous visits. You can find more information in Google's privacy policy.\n\n3. Security: We do not share your data with third parties, except as necessary to provide the service (e.g., Google AdSense).\n\n4. Your Rights: You have the right to delete data from local storage by clearing your browser's cache.",
        errorTitle: "Error",
        unknownError: "An unknown error occurred.",
        countdownFinishedText: "Ready for new reading",
        zodiacSignAries: "Aries",
        zodiacSignTaurus: "Taurus",
        zodiacSignGemini: "Gemini",
        zodiacSignCancer: "Cancer",
        zodiacSignLeo: "Leo",
        zodiacSignVirgo: "Virgo",
        zodiacSignLibra: "Libra",
        zodiacSignScorpio: "Scorpio",
        zodiacSignSagittarius: "Sagittarius",
        zodiacSignCapricorn: "Capricorn",
        zodiacSignAquarius: "Aquarius",
        zodiacSignPisces: "Pisces",
    },
    sr: {
        headerSubtitle: "Otkrijte šta vam zvezde i karte poručuju. Unesite vaš znak i pitanje kako biste dobili vaše personalizovano tarot čitanje.",
        formZodiacLabel: "Vaš Znak",
        formZodiacPlaceholder: "Izaberite znak...",
        formZodiacError: "Morate izabrati validan horoskopski znak.",
        formQuestionLabel: "Vaše pitanje za karte",
        formQuestionPlaceholder: "Šta vas muči ili zanima?",
        buttonDefault: "Šta kažu karte?",
        buttonLoading: "Mešanje karata...",
        resultsTitle: "Vaše Karte Sudbine",
        resultsReadingTitle: "Vaše Tarot Čitanje",
        resultsLoadingText: "Karte se mešaju, vaša sudbina se otkriva...",
        footerCopyright: "Sva prava zadržana.",
        footerAbout: "O Nama",
        footerMission: "Naša Misija",
        footerFaq: "Česta Pitanja",
        footerTerms: "Uslovi Korišćenja",
        footerPrivacy: "Politika Privatnosti",
        aboutDialogTitle: "O Quick Tarot Aplikaciji",
        aboutDialogContent: "Dobrodošli u Quick Tarot, vaš digitalni prozor u svet tarot karata. Naša misija je da pružimo intuitivno i personalizovano tarot iskustvo dostupno svima, bilo gde i bilo kada.\n\nKoristeći snagu veštačke inteligencije, naša aplikacija generiše jedinstvena i pronicljiva tarot čitanja. Svako čitanje je zasnovano na kartama nasumično izvučenim specijalno za vas i vaše pitanje, osiguravajući da dobijete poruku koja je vama namenjena.\n\nVerujemo da tarot nije samo predviđanje budućnosti, već alat za samorefleksiju i dublje razumevanje sadašnjosti. Bilo da tražite odgovore, inspiraciju ili jednostavno želite da istražite svoju intuiciju, Quick Tarot je tu da vas vodi.\n\nHvala vam što ste deo našeg putovanja.",
        missionDialogTitle: "Naša Misija",
        missionDialogContent: "Naša misija je da demistifikujemo tarot i učinimo ga dostupnim alatom za lični rast i introspekciju. Kroz spoj drevne mudrosti i moderne tehnologije, cilj nam je da osnažimo pojedince da pronađu jasnoću, donesu bolje odluke i razumeju dublje tokove svojih života.\n\nTežimo stvaranju sigurnog i podržavajućeg prostora gde svako može istražiti svoju intuiciju bez predrasuda.",
        faqDialogTitle: "Često Postavljana Pitanja",
        faqDialogContent: "P: Da li su čitanja zaista nasumična?\nA: Apsolutno. Za svako novo pitanje, naš sistem nasumično bira tri karte iz punog špila od 78 karata, garantujući jedinstveno i nepristrasno čitanje svaki put.\n\nP: Koliko često mogu da postavim pitanje?\nA: Kako bismo osigurali kvalitet i smislenost svakog čitanja, uveli smo vremensko ograničenje. Možete zatražiti novo čitanje svaka dva minuta.\n\nP: Da li je ovo pravo proricanje sudbine?\nA: Mi vidimo tarot kao vodič i sredstvo za samorefleksiju, a ne kao konkretno predviđanje budućnosti. Karte vam mogu pomoći da sagledate situaciju iz nove perspektive i donesete odluke koje su u skladu sa vašim unutrašnjim bićem.",
        termsDialogTitle: "Uslovi Korišćenja",
        termsDialogContent: "Pristupanjem i korišćenjem Quick Tarot aplikacije, slažete se sa sledećim uslovima:\n\n1. Usluga se pruža 'takva kakva jeste'. Čitanja su generisana od strane veštačke inteligencije i služe isključivo u zabavne i introspektivne svrhe. Ne treba ih smatrati profesionalnim, pravnim, medicinskim ili finansijskim savetom.\n\n2. Ne preuzimamo odgovornost za bilo kakve odluke koje donesete na osnovu informacija dobijenih putem naše aplikacije.\n\n3. Zadržavamo pravo da izmenimo ili prekinemo uslugu u bilo kom trenutku bez prethodne najave.\n\n4. Prikupljamo minimalne podatke neophodne za funkcionisanje aplikacije, što je opisano u našoj politici privatnosti.",
        privacyDialogTitle: "Politika Privatnosti",
        privacyDialogContent: "Ova Politika Privatnosti objašnjava kako prikupljamo, koristimo i štitimo vaše podatke.\n\n1. Prikupljanje podataka: Prikupljamo samo neophodne podatke za rad aplikacije, kao što su vaše pitanje i izabrani horoskopski znak, koji se ne čuvaju trajno. Koristimo lokalno skladište (local storage) u vašem pregledaču kako bismo sačuvali vaše poslednje čitanje i vreme kada možete zatražiti novo.\n\n2. Google AdSense: Koristimo Google AdSense za prikazivanje oglasa. Google može koristiti kolačiće za serviranje relevantnih oglasa na osnovu vaših prethodnih poseta. Više informacija možete pronaći u Google-ovoj politici privatnosti.\n\n3. Bezbednost: Ne delimo vaše podatke sa trećim stranama, osim ako je to neophodno za pružanje usluge (npr. Google AdSense).\n\n4. Vaša prava: Imate pravo da obrišete podatke iz lokalnog skladišta brisanjem keša vašeg pregledača.",
        errorTitle: "Greška",
        unknownError: "Došlo je do nepoznate greške.",
        countdownFinishedText: "Spremno za novo čitanje",
        zodiacSignAries: "Ovan",
        zodiacSignTaurus: "Bik",
        zodiacSignGemini: "Blizanci",
        zodiacSignCancer: "Rak",
        zodiacSignLeo: "Lav",
        zodiacSignVirgo: "Devica",
        zodiacSignLibra: "Vaga",
        zodiacSignScorpio: "Škorpija",
        zodiacSignSagittarius: "Strelac",
        zodiacSignCapricorn: "Jarac",
        zodiacSignAquarius: "Vodolija",
        zodiacSignPisces: "Ribe",
    }
};

// Fallback to English if the language is not found
export function getTranslations(langCode: string): TranslationSet {
    return ALL_TRANSLATIONS[langCode] || ALL_TRANSLATIONS.en;
}
